In [6]:
import pandas as pd

# 读取csv文件
df = pd.read_csv('./data/movie_top250.csv',usecols=['电影名','电影评分'])

# 数据处理

# 数据写入csv文件 --- index=False 不写入索引列
df.to_csv('./data/movie_top250_new.csv',index=False)

In [ ]:
#数据查看---> head,tail,describe,info,shape,columns
df1=pd.read_csv('./data/movie_top250.csv',usecols=['电影名','电影发布年份','电影评分'])

#print(df1.head(10)) #查看前10条数据
#df1.tail(10) #查看后10条数据
#df1.describe() #查看数据的描述性统计信息
#df1.info() #查看数据的数据类型和数据个数
#df1.shape #查看数据的形状
#df1.columns #查看数据的列名

#选择行
#2.1 iloc --->  基于行好选择  df.iloc[start:stop:step]
df1.iloc[0:5:1]  #不包含结束位置
df1.iloc[0:5]

#2.2 loc ---> 基于行索引选择行，loc[start:stop:step]
df1.loc[0:5]

                   电影名  电影发布年份  电影评分
0           安昂传奇：最后的气宗  (2026)    91
1              奇幻变身大冒险  (2026)    89
2              不期而遇的姐妹  (2026)    89
3                 夜巡毒枭  (2026)    88
4  鬼灭之刃：无限城篇 第一章 猗窝座再袭  (2025)    88
5               肖申克的救赎  (1994)    87

In [ ]:
df3=pd.read_csv('./data/movie_top250.csv')

# 配置项，展示所有的数据
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

#数据过滤--->df[filter]
# 获取电影分数大于85的电影
df3[df3['电影评分']>85]
#print(df4)

# 获取电影语言为英语或日语的电影
df3[df3['电影语言'].isin(['英语','日语'])]

# 获取电影评分在80到85之间的电影  between-->包含80和85
df3[df3['电影评分'].between(80,85)]

# 获取电影语言为英语且评分大于85的电影
df3[(df3['电影语言']=='英语')&(df3['电影评分']>85)]

# 获取电影语言为英语或日语且电影发布年份2025或2026的电影
df3[(df3['电影语言'].isin(['英语','日语']))&(df3['电影发布年份'].isin(['(2025)','(2026)']))]

#print(df5)

,电影名,电影发布年份,电影上映时间,电影类型,电影时长,电影评分,电影语言,电影导演,电影作者,电影宣传语,电影简介
0,安昂传奇：最后的气宗,(2026),2026-07-24 (US),"动画,冒险,奇幻,动作",1h 39m,91,英语,Tim Hedrick,劳伦·蒙哥马利,The legacy reawakens.,派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,内森·格雷诺,Robert Snow,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,外崎春雄,近藤光,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
7,迈克尔·杰克逊：巨星之路,(2026),2026-04-24 (CN),"音乐,剧情",2h 16m,86,英语,安东尼·福奎阿,约翰·洛根,Discover the making of a king.,本片将通过一段从未展现过的深度视角，真实记录传奇巨星迈克尔·杰克逊的复杂人生。影片不仅再现了...
8,挽救计划,(2026),2026-03-20 (CN),"科幻,冒险",2h 36m,86,英语,菲尔·洛德,克里斯托弗·米勒,信念是暗夜唯一的光,太阳正在被“吃”掉，绝望吞噬地球。一名“平凡”的中学教师格雷斯（瑞恩·高斯林 饰）背负全人类...
13,电锯人剧场版：蕾塞篇,(2025),2025-09-19 (JP),"动画,动作,爱情,奇幻",1h 40m,85,日语,吉原达矢,濑古浩司,活出你的人生本色……并让它精彩纷呈。,故事延续TV动画的最终章，讲述男主角电次在偶然邂逅的神秘少女蕾塞的庇护下，在快节奏的战斗中，...
40,幸运有八只触手,(2026),2026-05-08 (US),"剧情,悬疑",1h 51m,84,英语,奥利维亚·纽曼,约翰·惠廷顿,Brighter together.,一名寡妇在小镇水族馆值夜班，与一只聪明的章鱼及一个迷茫的年轻人培养出独特情谊。
52,保护者,(2026),2026-03-06 (US),"动作,惊悚",1h 32m,84,英语,阿德里安·格鲁伯格,Mun-Bong Seub,Never get between a mother and her child.,退役军人尼基与女儿克洛伊平静生活，却在废弃工厂醒来后发现女儿遭绑架，她必须重返黑暗世界，对抗...
60,玩具总动员5,(2026),2026-06-19 (CN),"动画,家庭,喜剧,冒险",1h 42m,84,英语,安德鲁·斯坦顿,Kenna Harris,大战开启,胡迪、巴斯光年、翠斯等“元老级”玩具将跟随小主人邦妮的成长脚步，共同迎接数字时代下的全新挑战...
78,真爱留声,(2026),2026-06-20 (US),"爱情,喜剧,剧情",1h 59m,83,英语,Leah McKendrick,NaN,Sometimes the universe leaves you a message.,年轻女子给已故姐姐发送的搞笑自白语音留言无意中被转给了陌生人，而这个陌生人竟隔着遥远的距离爱...
89,惩罚者：最后一击,(2026),2026-05-12 (US),"动作,剧情,犯罪",51m,83,英语,雷纳尔多·马库斯·格林,老约翰·维克多·罗米塔,Hey Frank.,失去家人多年后，弗兰克·卡塞尔依然被过去的创伤与幻象困扰，试图远离曾经作为“惩罚者”的暴力人...