In [ ]:
import pandas as pd
pd.set_option('display.min_rows', 30) #设置显示行数

#1. 读取数据
df = pd.read_csv('./data/movie_top250.csv')

#2. 数据清洗
#2.1 缺失值处理
#df.isnull() #查看缺失值

#2.1.1 删除缺失值
#df.dropna()  #删除缺失值所在行
#df=df.dropna(axis=1) #删除缺失值所在列
#df

#2.1.2 填充缺失值
#df.fillna('未知') #填充缺失值为'未知'
#df.ffill() #填充缺失值，填充上一行数据
#df.bfill() #填充缺失值，填充下一行数据

#2.2 重复值处理
#2.2.1 查看重复值
df.duplicated() #查看重复值（默认检查所有列）
df.duplicated(subset=['电影上映时间']) #查看重复值（只检查指定列）

#2.2.2 删除重复值
df.drop_duplicates(subset=['电影上映时间'],keep='last') #删除重复值,keep='last'保留最后一个重复值,keep='first'保留第一个重复值,keep=False删除所有重复值

,电影名,电影发布年份,电影上映时间,电影类型,电影时长,电影评分,电影语言,电影导演,电影作者,电影宣传语,电影简介
0,安昂传奇：最后的气宗,(2026),2026-07-24 (US),"动画,冒险,奇幻,动作",1h 39m,91,英语,Tim Hedrick,劳伦·蒙哥马利,The legacy reawakens.,派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,内森·格雷诺,Robert Snow,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
2,不期而遇的姐妹,(2026),2026-03-12 (MX),"喜剧,爱情",1h 25m,89,西班牙语,Ihtzi Hurtado,Carmen Castro,简介,两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。
3,夜巡毒枭,(2026),2026-08-21 (MX),"犯罪,动作,惊悚",1h 31m,88,西班牙语,Chava Cartas,Bernardo Esquinca,简介,两位墨西哥员警不幸得罪一名残忍的毒枭后，必须拼命撑过值勤的最后几小时。改编自真实事件。
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,外崎春雄,近藤光,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
5,肖申克的救赎,(1994),2026-08-28 (CN),"剧情,犯罪",2h 22m,87,英语,弗兰克·德拉邦特,斯蒂芬·金,恐惧会将你囚禁，希望则能让你获得自由。,1947年，银行家安迪·杜佛兰因被控杀害妻子及其情人，尽管始终坚称清白，仍被判处两项无期徒刑...
6,教父,(1972),1972-03-24 (US),"剧情,犯罪",2h 55m,87,英语,弗朗西斯·科波拉,马里奥·普佐,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...
7,迈克尔·杰克逊：巨星之路,(2026),2026-04-24 (CN),"音乐,剧情",2h 16m,86,英语,安东尼·福奎阿,约翰·洛根,Discover the making of a king.,本片将通过一段从未展现过的深度视角，真实记录传奇巨星迈克尔·杰克逊的复杂人生。影片不仅再现了...
8,挽救计划,(2026),2026-03-20 (CN),"科幻,冒险",2h 36m,86,英语,菲尔·洛德,克里斯托弗·米勒,信念是暗夜唯一的光,太阳正在被“吃”掉，绝望吞噬地球。一名“平凡”的中学教师格雷斯（瑞恩·高斯林 饰）背负全人类...
9,教父2,(1974),1974-12-20 (US),"剧情,犯罪",3h 20m,86,英语,弗朗西斯·科波拉,马里奥·普佐,柯里昂帝国的兴衰史。,作为《教父》的续篇，影片延续了科莱昂家族两代权力交替的史诗。科波拉在第二部分中讲述了两条故事...
10,十二怒汉,(1957),1957-04-10 (US),剧情,1h 36m,86,英语,雷金纳德·罗斯,西德尼·吕美特,命悬其手，死视其意,西德尼·吕美特执导的本片堪称电影史上最颠覆的法庭剧。这部改编自雷金纳德·罗斯电视剧的经典之作...
11,辛德勒的名单,(1993),2019-04-06 (CN),"剧情,历史,战争",3h 15m,86,英语,史蒂文·斯皮尔伯格,托马斯·肯尼利,谁拯救了一条生命，谁就拯救了整个世界。,1939年，纳粹德国入侵波兰。德国商人奥斯卡·辛德勒来到被占领的克拉科夫，利用自己的人脉和金...
12,年轻的心,(2024),2024-12-18 (BE),"剧情,爱情",1h 37m,86,荷兰语,安东尼·沙特曼,NaN,简介,埃利亚斯是一个十四岁的男孩，在一个小村庄长大，他在这里感到自己像个局外人。在遇到新邻居兼同龄...
13,电锯人剧场版：蕾塞篇,(2025),2025-09-19 (JP),"动画,动作,爱情,奇幻",1h 40m,85,日语,吉原达矢,濑古浩司,活出你的人生本色……并让它精彩纷呈。,故事延续TV动画的最终章，讲述男主角电次在偶然邂逅的神秘少女蕾塞的庇护下，在快节奏的战斗中，...
14,蝙蝠侠：黑暗骑士,(2008),2018-04-07 (CN),"动作,惊悚",2h 32m,85,英语,克里斯托弗·诺兰,鲍勃·凯恩,黎明前的夜是最黑暗的！,在蝙蝠侠、警官詹姆斯·戈登和地方检察官哈维·丹特的共同努力下，哥谭市的犯罪势力受到前所未有的...
...,...,...,...,...,...,...,...,...,...,...,...
83,五等分的新娘 剧场版,(2022),2022-05-20 (JP),"动画,喜剧,爱情",2h 16m,83,日语,神保昌登,大知庆一郎,简介,为了让「濒临留级」又「讨厌学习」的美少女五姐妹通过学校考试毕业，主角风太郎以兼职家庭教师的身...
84,献给我的前妻,(2019),2019-11-08 (EC),"剧情,喜剧",1h 34m,83,西班牙语,Jorge Ulloa,Diego Ulloa,简介,这部电影讲述了21岁的阿里尔的故事：为筹钱挽回濒临破裂的恋情、与前女友重逢，他决定组建一支摇...
85,我们如此相爱,(1974),1974-12-21 (IT),"剧情,喜剧",2h 4m,83,意大利语,埃托雷·斯科拉,艾根诺尔·因克鲁西,一件光彩夺目的事物。,安东尼奥（尼诺·曼弗莱迪 Nino Manfredi 饰）、贾尼（维托里奥·加斯曼 Vitt...
86,大独裁者,(1940),2021-09-19 (CN),"喜剧,战争",2h 5m,83,英语,查理·卓别林,NaN,再次——全世界都在嘲笑！,在其备受争议的杰作中，查理·卓别林既尖刻地讽刺了阿道夫·希特勒，又巧妙地颠覆了自身的喜剧形象...
87,摩登时代,(1936),1936-09-17 (CN),"喜剧,剧情,爱情",1h 27m,83,英语,查理·卓别林,NaN,他是现代最伟大的艺人，举世无双！世上无人能像他那样，让你开怀大笑，又深深触动你的心弦……全世...,二十年代的美国处于经济萧条时期，失业率居高不下，工人受尽压榨，成为了大机器生产中的一颗螺丝钉...
88,夜与雾,(1956),1956-05-22 (FR),"纪录,历史",32m,83,法语,阿伦·雷乃,让·凯罗尔,简介,1956年导演阿伦•雷乃用摄影机带领观众重回奥斯维辛。当年纳粹集中营的旧址上已是一片祥和美丽...
89,惩罚者：最后一击,(2026),2026-05-12 (US),"动作,剧情,犯罪",51m,83,英语,雷纳尔多·马库斯·格林,老约翰·维克多·罗米塔,Hey Frank.,失去家人多年后，弗兰克·卡塞尔依然被过去的创伤与幻象困扰，试图远离曾经作为“惩罚者”的暴力人...
90,生活多美好,(1946),1946-12-20 (US),"剧情,家庭,奇幻",2h 11m,83,英语,弗兰克·卡普拉,阿尔伯特·莫里斯·哈克特,这笑声多么美妙！这爱意多么动人！,一位天使被派往人间，帮助一位万念俱灰的商人，向他展现假如他从未存在过，生活将会是怎样的光景。
91,从天而降,(2019),2019-12-24 (MX),"喜剧,剧情,音乐",1h 52m,83,西班牙语,Pepe Bojórquez,Alfredo Felix-Diaz,简介,墨西哥传奇人物佩德罗·因凡特（Pedro Infante）在地球上又获得了一次机会，可以为自...
92,触不可及,(2011),2011-11-02 (FR),"剧情,喜剧",1h 52m,83,法语,埃里克·托莱达诺,奥利维埃·纳卡什,Sometimes you have to reach into someone else'...,富有的菲利普因一场滑翔伞事故导致高位瘫痪，需要招聘一名全职陪护。前来应聘的人络绎不绝，却始终...
94,边境奇袭,(2025),2025-02-28 (MX),"动作,冒险,惊悚",1h 25m,83,西班牙语,Chava Cartas,José Rubén Escalante Méndez,简介,一场人质营救行动带来了新的敌人，格雷罗上尉和他的精英士兵们必须应对残忍犯罪团伙的埋伏。
96,萤火之森,(2011),2011-09-17 (JP),"爱情,动画,奇幻",44m,83,日语,大森贵弘,NaN,我已经等不到夏天了,某年夏天，6岁小女孩竹川萤来到爷爷家度假，她闯进了传说住满妖怪的山神森林。正当她因为迷路而焦...
97,现代启示录,(1979),1979-05-19 (CN),"剧情,战争",3h 22m,83,英语,弗朗西斯·科波拉,约瑟夫·康拉德,这就是终点...,越战期间，威拉德上尉受命执行一项危险任务，深入柬埔寨刺杀一位脱离建制的叛变上校——此人已在当...
98,新世纪福音战士剧场版：Air／真心为你,(1997),1997-07-19 (JP),"动画,科幻,剧情,奇幻,动作",1h 27m,83,日语,庵野秀明,鹤卷和哉,毁灭的命运亦是重生的喜悦。,《新世纪福音战士》系列第二部剧场版，于 1997 年 7 月 19 日在日本上映。全名：《新...
99,黑客帝国,(1999),2000-01-14 (CN),"动作,科幻",2h 16m,83,英语,莉莉·沃卓斯基,拉娜·沃卓斯基,欢迎来到现实世界,不久的将来，网络黑客尼奥对这个看似正常的现实世界产生了怀疑。他结识了黑客崔妮蒂，并见到了黑客...

In [ ]:
#2.3 异常值处理
#2.3.1 查看异常值
df[df['电影发布年份']=='(2025)']

#2.3.2 删除异常值
df.drop(df[df['电影发布年份']=='(2025)'].index)

#2.3.3 替换异常值
df['电影发布年份'].replace('(2025)',2025,inplace=True)

,电影名,电影发布年份,电影上映时间,电影类型,电影时长,电影评分,电影语言,电影导演,电影作者,电影宣传语,电影简介
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,外崎春雄,近藤光,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
13,电锯人剧场版：蕾塞篇,(2025),2025-09-19 (JP),"动画,动作,爱情,奇幻",1h 40m,85,日语,吉原达矢,濑古浩司,活出你的人生本色……并让它精彩纷呈。,故事延续TV动画的最终章，讲述男主角电次在偶然邂逅的神秘少女蕾塞的庇护下，在快节奏的战斗中，...
64,鱿鱼游戏： 第二季 制作特辑,(2025),2025-01-03 (KR),纪录,28m,83,朝鲜语,NaN,NaN,简介,三年前，鱿鱼游戏由456号选手（李政宰 饰）胜出，他本想远走高飞，却在搭机赴美前临阵反悔，决...
94,边境奇袭,(2025),2025-02-28 (MX),"动作,冒险,惊悚",1h 25m,83,西班牙语,Chava Cartas,José Rubén Escalante Méndez,简介,一场人质营救行动带来了新的敌人，格雷罗上尉和他的精英士兵们必须应对残忍犯罪团伙的埋伏。

In [11]:
#2.4数据格式转换
df['电影时长']=df['电影时长'].str.replace('分钟','')
df

,电影名,电影发布年份,电影上映时间,电影类型,电影时长,电影评分,电影语言,电影导演,电影作者,电影宣传语,电影简介
0,安昂传奇：最后的气宗,(2026),2026-07-24 (US),"动画,冒险,奇幻,动作",1h 39m,91,英语,Tim Hedrick,劳伦·蒙哥马利,The legacy reawakens.,派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...
1,奇幻变身大冒险,(2026),2026-05-01 (US),"冒险,动画,家庭,奇幻",1h 42m,89,英语,内森·格雷诺,Robert Snow,Transform your destiny.,森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。
2,不期而遇的姐妹,(2026),2026-03-12 (MX),"喜剧,爱情",1h 25m,89,西班牙语,Ihtzi Hurtado,Carmen Castro,简介,两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。
3,夜巡毒枭,(2026),2026-08-21 (MX),"犯罪,动作,惊悚",1h 31m,88,西班牙语,Chava Cartas,Bernardo Esquinca,简介,两位墨西哥员警不幸得罪一名残忍的毒枭后，必须拼命撑过值勤的最后几小时。改编自真实事件。
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,(2025),2025-11-14 (CN),"动画,动作,奇幻",2h 35m,88,日语,外崎春雄,近藤光,It's time to have some fun.,当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...
5,肖申克的救赎,(1994),2026-08-28 (CN),"剧情,犯罪",2h 22m,87,英语,弗兰克·德拉邦特,斯蒂芬·金,恐惧会将你囚禁，希望则能让你获得自由。,1947年，银行家安迪·杜佛兰因被控杀害妻子及其情人，尽管始终坚称清白，仍被判处两项无期徒刑...
6,教父,(1972),1972-03-24 (US),"剧情,犯罪",2h 55m,87,英语,弗朗西斯·科波拉,马里奥·普佐,一份你无法拒绝的邀约。,40年代的美国，“教父”维托·唐·柯里昂是黑手党柯里昂家族的首领，带领家族从事非法的勾当，但...
7,迈克尔·杰克逊：巨星之路,(2026),2026-04-24 (CN),"音乐,剧情",2h 16m,86,英语,安东尼·福奎阿,约翰·洛根,Discover the making of a king.,本片将通过一段从未展现过的深度视角，真实记录传奇巨星迈克尔·杰克逊的复杂人生。影片不仅再现了...
8,挽救计划,(2026),2026-03-20 (CN),"科幻,冒险",2h 36m,86,英语,菲尔·洛德,克里斯托弗·米勒,信念是暗夜唯一的光,太阳正在被“吃”掉，绝望吞噬地球。一名“平凡”的中学教师格雷斯（瑞恩·高斯林 饰）背负全人类...
9,教父2,(1974),1974-12-20 (US),"剧情,犯罪",3h 20m,86,英语,弗朗西斯·科波拉,马里奥·普佐,柯里昂帝国的兴衰史。,作为《教父》的续篇，影片延续了科莱昂家族两代权力交替的史诗。科波拉在第二部分中讲述了两条故事...
10,十二怒汉,(1957),1957-04-10 (US),剧情,1h 36m,86,英语,雷金纳德·罗斯,西德尼·吕美特,命悬其手，死视其意,西德尼·吕美特执导的本片堪称电影史上最颠覆的法庭剧。这部改编自雷金纳德·罗斯电视剧的经典之作...
11,辛德勒的名单,(1993),2019-04-06 (CN),"剧情,历史,战争",3h 15m,86,英语,史蒂文·斯皮尔伯格,托马斯·肯尼利,谁拯救了一条生命，谁就拯救了整个世界。,1939年，纳粹德国入侵波兰。德国商人奥斯卡·辛德勒来到被占领的克拉科夫，利用自己的人脉和金...
12,年轻的心,(2024),2024-12-18 (BE),"剧情,爱情",1h 37m,86,荷兰语,安东尼·沙特曼,NaN,简介,埃利亚斯是一个十四岁的男孩，在一个小村庄长大，他在这里感到自己像个局外人。在遇到新邻居兼同龄...
13,电锯人剧场版：蕾塞篇,(2025),2025-09-19 (JP),"动画,动作,爱情,奇幻",1h 40m,85,日语,吉原达矢,濑古浩司,活出你的人生本色……并让它精彩纷呈。,故事延续TV动画的最终章，讲述男主角电次在偶然邂逅的神秘少女蕾塞的庇护下，在快节奏的战斗中，...
14,蝙蝠侠：黑暗骑士,(2008),2018-04-07 (CN),"动作,惊悚",2h 32m,85,英语,克里斯托弗·诺兰,鲍勃·凯恩,黎明前的夜是最黑暗的！,在蝙蝠侠、警官詹姆斯·戈登和地方检察官哈维·丹特的共同努力下，哥谭市的犯罪势力受到前所未有的...
...,...,...,...,...,...,...,...,...,...,...,...
85,我们如此相爱,(1974),1974-12-21 (IT),"剧情,喜剧",2h 4m,83,意大利语,埃托雷·斯科拉,艾根诺尔·因克鲁西,一件光彩夺目的事物。,安东尼奥（尼诺·曼弗莱迪 Nino Manfredi 饰）、贾尼（维托里奥·加斯曼 Vitt...
86,大独裁者,(1940),2021-09-19 (CN),"喜剧,战争",2h 5m,83,英语,查理·卓别林,NaN,再次——全世界都在嘲笑！,在其备受争议的杰作中，查理·卓别林既尖刻地讽刺了阿道夫·希特勒，又巧妙地颠覆了自身的喜剧形象...
87,摩登时代,(1936),1936-09-17 (CN),"喜剧,剧情,爱情",1h 27m,83,英语,查理·卓别林,NaN,他是现代最伟大的艺人，举世无双！世上无人能像他那样，让你开怀大笑，又深深触动你的心弦……全世...,二十年代的美国处于经济萧条时期，失业率居高不下，工人受尽压榨，成为了大机器生产中的一颗螺丝钉...
88,夜与雾,(1956),1956-05-22 (FR),"纪录,历史",32m,83,法语,阿伦·雷乃,让·凯罗尔,简介,1956年导演阿伦•雷乃用摄影机带领观众重回奥斯维辛。当年纳粹集中营的旧址上已是一片祥和美丽...
89,惩罚者：最后一击,(2026),2026-05-12 (US),"动作,剧情,犯罪",51m,83,英语,雷纳尔多·马库斯·格林,老约翰·维克多·罗米塔,Hey Frank.,失去家人多年后，弗兰克·卡塞尔依然被过去的创伤与幻象困扰，试图远离曾经作为“惩罚者”的暴力人...
90,生活多美好,(1946),1946-12-20 (US),"剧情,家庭,奇幻",2h 11m,83,英语,弗兰克·卡普拉,阿尔伯特·莫里斯·哈克特,这笑声多么美妙！这爱意多么动人！,一位天使被派往人间，帮助一位万念俱灰的商人，向他展现假如他从未存在过，生活将会是怎样的光景。
91,从天而降,(2019),2019-12-24 (MX),"喜剧,剧情,音乐",1h 52m,83,西班牙语,Pepe Bojórquez,Alfredo Felix-Diaz,简介,墨西哥传奇人物佩德罗·因凡特（Pedro Infante）在地球上又获得了一次机会，可以为自...
92,触不可及,(2011),2011-11-02 (FR),"剧情,喜剧",1h 52m,83,法语,埃里克·托莱达诺,奥利维埃·纳卡什,Sometimes you have to reach into someone else'...,富有的菲利普因一场滑翔伞事故导致高位瘫痪，需要招聘一名全职陪护。前来应聘的人络绎不绝，却始终...
93,日落大道,(1950),2026-04-16 (CN),剧情,1h 50m,83,英语,比利·怀尔德,查尔斯·威廉·布莱克特,一个好莱坞故事。,好莱坞的声名终会消散——只需问问诺玛·戴斯蒙德。她曾是影坛传奇，如今已成被人遗忘的旧时代残影...
94,边境奇袭,(2025),2025-02-28 (MX),"动作,冒险,惊悚",1h 25m,83,西班牙语,Chava Cartas,José Rubén Escalante Méndez,简介,一场人质营救行动带来了新的敌人，格雷罗上尉和他的精英士兵们必须应对残忍犯罪团伙的埋伏。
95,西部往事,(1968),2018-04-16 (CN),"剧情,西部",2h 46m,83,意大利语,赛尔乔·莱昂内,塞尔吉奥·多纳蒂,她生命中有三个男人。一个带走了她，一个深爱着她，还有一个——最终杀死了她。,塞尔吉奥·莱昂内的这部不朽史诗，其恢弘堪比取景地纪念碑谷，其气度媲美星光熠熠的杰出演员阵容，...
96,萤火之森,(2011),2011-09-17 (JP),"爱情,动画,奇幻",44m,83,日语,大森贵弘,NaN,我已经等不到夏天了,某年夏天，6岁小女孩竹川萤来到爷爷家度假，她闯进了传说住满妖怪的山神森林。正当她因为迷路而焦...
97,现代启示录,(1979),1979-05-19 (CN),"剧情,战争",3h 22m,83,英语,弗朗西斯·科波拉,约瑟夫·康拉德,这就是终点...,越战期间，威拉德上尉受命执行一项危险任务，深入柬埔寨刺杀一位脱离建制的叛变上校——此人已在当...
98,新世纪福音战士剧场版：Air／真心为你,(1997),1997-07-19 (JP),"动画,科幻,剧情,奇幻,动作",1h 27m,83,日语,庵野秀明,鹤卷和哉,毁灭的命运亦是重生的喜悦。,《新世纪福音战士》系列第二部剧场版，于 1997 年 7 月 19 日在日本上映。全名：《新...
99,黑客帝国,(1999),2000-01-14 (CN),"动作,科幻",2h 16m,83,英语,莉莉·沃卓斯基,拉娜·沃卓斯基,欢迎来到现实世界,不久的将来，网络黑客尼奥对这个看似正常的现实世界产生了怀疑。他结识了黑客崔妮蒂，并见到了黑客...